@baseUrl= http://localhost:5000/auth

POST {{baseUrl}}/register
Content-Type: application/json
 
{
    "name": "Samuele",
      "surname": "Calabrese",
      "email": "samu@calab.com",
      "avatar": "",
      "password":"1234567890"
} 

###
POST {{baseUrl}}/login
Content-Type: application/json
 
{
      "email": "samu@calab.com",
      "password":"1234567890"
} 

###

GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDFmZTM0NmI0NWEwYTE5NDM5Yjg5ZiIsImlhdCI6MTcyNTAzODUzOCwiZXhwIjoxNzI1MDQyMTM4fQ.DF3JIL_H0UztsdXz3-Kv_Q6KLHbIBsq51vERu0DGscY
