@baseUrl= http://localhost:5000/auth

POST {{baseUrl}}/register
Content-Type: application/json
 
{
    "name": "Dario",
      "surname": "Patti",
      "email": "dario@patti.com",
      "avatar": "",
      "password":"12345"
} 

###
POST {{baseUrl}}/login
Content-Type: application/json
 
{
      "email": "pippo@pippo.com",
      "password":"pippopippo"
} 

###

GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDQ4MzQ5ZjY4ODhmNTVlNTU4OGJiNyIsImlhdCI6MTcyNTQ0NjM0NSwiZXhwIjoxNzI1NDQ5OTQ1fQ.3_UhhvtVc7b0m095YE9KP6O-k8T3aRwSWX4mt6mxp2k

###

DELETE {{baseUrl}}/66d6d25431572436f6eb8ea4