@baseUrl= http://localhost:5000/authors

GET {{baseUrl}}

###

GET {{baseUrl}}/66d1cf98c91a0ac1fe5d7b1a

###

POST {{baseUrl}}
Content-Type: application/json
 
{
    "name": "Patrizia",
      "surname": "Patti",
      "email": "patti@patti.com",
      "avatar": "",
      "password":"asdqwe"
} 

###

PUT {{baseUrl}}/66c62f5823cdebec0a1b54be
Content-Type: application/json

{
    "name": "Antonio",
    "surname": "Fedele",
    "email": "antonio@fedele.com",
    "avatar": "antofedele"
} 


###

DELETE {{baseUrl}}/66d1c325d4400220a5f7762f