@baseUrl= http://localhost:5000/authors

GET {{baseUrl}}

###

GET {{baseUrl}}/66b37b264b2317729dc8dc17

###

POST {{baseUrl}}
Content-Type: application/json
 
{
    "name": "gabriele",
    "surname": "p",
    "email": "gabriele@p.com",
    "birthDate":  "1988-11-14",
    "avatar": "gbpzz"
} 

###

PUT {{baseUrl}}/66b37b264b2317729dc8dc17
Content-Type: application/json

{
    "name": "Patrizia",
    "surname": "Patti",
    "email": "patrizia@patti.com",
    "birthDate":  "1986-08-18",
    "avatar": "pattip"
} 


###

DELETE {{baseUrl}}/66bb0f70c6dddc1c68432f11
