@baseUrl= http://localhost:5000/auth

POST {{baseUrl}}/register
Content-Type: application/json
 
{
    "name": "Dario",
      "surname": "Patti",
      "email": "dario@patti.com",
      "avatar": "",
      "password":"12345"
} 

###
POST {{baseUrl}}/login
Content-Type: application/json
 
{
      "email": "patrizia@patti.com",
      "password":"qwerty1234"
} 

###

GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDFmZTM0NmI0NWEwYTE5NDM5Yjg5ZiIsImlhdCI6MTcyNTAzODUzOCwiZXhwIjoxNzI1MDQyMTM4fQ.DF3JIL_H0UztsdXz3-Kv_Q6KLHbIBsq51vERu0DGscY
