@baseUrl= http://localhost:5000/blogPosts


###

GET {{baseUrl}}/66d72fbd4ff3bf23f1ad549b/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDZjNzkyNDM5N2ZiYjFlNDI0YjNlYyIsImlhdCI6MTcyNTYzNjI4MywiZXhwIjoxNzI1Njc5NDgzfQ.vdWw1NbU_ASwmvFTbKEurMc5gASWuzYxMbspyAlaDXI
###

GET {{baseUrl}}/66d705b465e41fed284b3864/comments/66d835c588a0be306fdcab14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDQ4MzQ5ZjY4ODhmNTVlNTU4OGJiNyIsImlhdCI6MTcyNTQ0NjM0NSwiZXhwIjoxNzI1NDQ5OTQ1fQ.3_UhhvtVc7b0m095YE9KP6O-k8T3aRwSWX4mt6mxp2k

###

POST {{baseUrl}}/66d9916a171fe5c5f256743d/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDZjNzkyNDM5N2ZiYjFlNDI0YjNlYyIsImlhdCI6MTcyNTczMzY4MCwiZXhwIjoxNzI1Nzc2ODgwfQ.QUt7opSekncgbUaKb3KQ98AvGbFWoKAxanike0U_Vbw
Content-Type: application/json
 
{
    "content": "commento difhggf pd",

} 

###

PUT {{baseUrl}}/66d705b465e41fed284b3864/comment/66d835c588a0be306fdcab14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDQ4MzQ5ZjY4ODhmNTVlNTU4OGJiNyIsImlhdCI6MTcyNTQ0NjM0NSwiZXhwIjoxNzI1NDQ5OTQ1fQ.3_UhhvtVc7b0m095YE9KP6O-k8T3aRwSWX4mt6mxp2k
Content-Type: application/json
 
{
    "content": "cambio il commento"
} 

###

DELETE {{baseUrl}}/66d705b465e41fed284b3864/comment/66d8369088a0be306fdcab31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDQ4MzQ5ZjY4ODhmNTVlNTU4OGJiNyIsImlhdCI6MTcyNTQ0NjM0NSwiZXhwIjoxNzI1NDQ5OTQ1fQ.3_UhhvtVc7b0m095YE9KP6O-k8T3aRwSWX4mt6mxp2k
