@baseUrl= http://localhost:5000/blogPosts

GET http://localhost:5000/blogPosts?title=ecco

###

GET {{baseUrl}}

###

GET {{baseUrl}}/66bb6c895c7771fd76ce69e0

###

POST {{baseUrl}}
Content-Type: application/json
 
{
    "category": "9876qws",
    "title": "9876",
    "cover": "url della cover",
    "readTime": {
        "value": 1,
        "unit": "min"
    },
    "author": "ilop",
    "content": "123456789"
} 

###

PUT {{baseUrl}}/66be004854862603acafd837
Content-Type: application/json

{
    "category": "0987",
    "title": "09",
    "cover": "url della cover",
    "readTime": {
        "value": 2,
        "unit": "min"
    },
    "author": "ilop",
    "content": "0987654321"
} 


###

DELETE {{baseUrl}}/66be004854862603acafd837
